const objProducts = [
  {
    name: "HyperX Alloy FPS Pro Mechanical Keyboard",
    price: 9999,
    description:
      "Mechanical gaming keyboard with customizable RGB backlighting.",
    stock: 50,
    images: ["https://drive.google.com/uc?id=1h_rrvW3_IXxxQ7KPan_y3Kf_FXtuRduW", "https://drive.google.com/uc?id=1yylwUxKb3wCJN0zhUwd6hMfJmAfVohhF"],
    brand: "HyperX",
    color: "Black",
    type: "Keyboard",
  },
  {
    name: "Logitech G Pro Wireless Gaming Mouse",
    price: 5999,
    description:
      "High-performance wireless mouse with 16000 DPI optical sensor.",
    stock: 30,
    images: ["https://drive.google.com/uc?id=1yclMDE2ZFXpU8FCl21uhhanLguu2ir1s", "https://drive.google.com/uc?id=1ol32RwZSoHVYO1QgkTpTMYE99FXbhUmT"],
    brand: "Logitech",
    color: "Red",
    type: "Mouse",
  },
  {
    name: "Razer Kraken X Gaming Headset",
    price: 12999,
    description:
      "7.1 surround sound gaming headset for an immersive gaming experience.",
    stock: 20,
    images: ["https://drive.google.com/uc?id=1Z01qBtlZHzrE-4IF0u2NvM5YMMz0aU6v", "https://drive.google.com/uc?id=1mLsfnn-O8Z3dXqn_JfSEGgFVujrQ-zDt"],
    brand: "Razer",
    color: "Black",
    type: "Headset",
  },
  {
    name: "Logitech G Pro X Mechanical Gaming Keyboard",
    price: 14999,
    description: "Mechanical gaming keyboard with customizable switches for pro-level performance.",
    stock: 15,
    images: ["https://drive.google.com/uc?id=1abc123def456", "https://drive.google.com/uc?id=2def456abc123"],
    brand: "Logitech",
    color: "Black",
    type: "Keyboard",
    },
    {
    name: "Samsung Galaxy S21 Ultra 5G Smartphone",
    price: 109999,
    description: "Flagship smartphone with a 108MP camera and 5G connectivity.",
    stock: 30,
    images: ["https://drive.google.com/uc?id=3ghi789jkl012", "https://drive.google.com/uc?id=4jkl012ghi789"],
    brand: "Samsung",
    color: "Phantom Black",
    type: "Smartphone",
    },
    {
    name: "Sony PlayStation 5 Gaming Console",
    price: 49999,
    description: "Next-gen gaming console with ray tracing and fast SSD storage.",
    stock: 10,
    images: ["https://drive.google.com/uc?id=5mno345pqr678", "https://drive.google.com/uc?id=6pqr678mno345"],
    brand: "Sony",
    color: "White",
    type: "Gaming Console",
    },
    {
    name: "Apple MacBook Air (M2 Chip) Laptop",
    price: 139999,
    description: "Ultra-thin laptop with Apple's M2 chip for exceptional performance.",
    stock: 25,
    images: ["https://drive.google.com/uc?id=7stuv890wxy123", "https://drive.google.com/uc?id=8wxy123stuv890"],
    brand: "Apple",
    color: "Space Gray",
    type: "Laptop",
    },
    {
    name: "Bose QuietComfort 35 II Wireless Headphones",
    price: 24999,
    description: "Noise-canceling wireless headphones for an immersive audio experience.",
    stock: 12,
    images: ["https://drive.google.com/uc?id=9zab456cde789", "https://drive.google.com/uc?id=0fgh123ijk456"],
    brand: "Bose",
    color: "Silver",
    type: "Headphones",
    },
    {
    name: "Dell Ultrasharp U2719D 27-Inch Monitor",
    price: 39999,
    description: "High-resolution 27-inch monitor for professional-grade visual clarity.",
    stock: 18,
    images: ["https://drive.google.com/uc?id=1lmnopqrs4560", "https://drive.google.com/uc?id=2xyz345abc678"],
    brand: "Dell",
    color: "Black",
    type: "Monitor",
    },
    {
    name: "GoPro Hero 10 Black Action Camera",
    price: 34999,
    description: "4K action camera with advanced stabilization for epic footage.",
    stock: 22,
    images: ["https://drive.google.com/uc?id=3defg456hij789", "https://drive.google.com/uc?id=4klm567nop012"],
    brand: "GoPro",
    color: "Black",
    type: "Action Camera",
    },
    {
    name: "Nike Air Zoom Pegasus 38 Running Shoes",
    price: 8999,
    description: "High-performance running shoes with responsive cushioning.",
    stock: 40,
    images: ["https://drive.google.com/uc?id=5nopqrs123tu678", "https://drive.google.com/uc?id=6vwx789yza890"],
    brand: "Nike",
    color: "Blue",
    type: "Running Shoes",
    },
    {
    name: "Canon EOS 90D DSLR Camera",
    price: 99999,
    description: "High-quality DSLR camera with 32.5MP sensor and 4K video recording.",
    stock: 8,
    images: ["https://drive.google.com/uc?id=7bcdefg890lmn012", "https://drive.google.com/uc?id=8opqrs456tuvw345"],
    brand: "Canon",
    color: "Black",
    type: "Camera",
    },
    {
    name: "Fitbit Charge 5 Fitness Tracker",
    price: 12999,
    description: "Advanced fitness tracker with heart rate monitoring and built-in GPS.",
    stock: 35,
    images: ["https://drive.google.com/uc?id=9xyz123abc456", "https://drive.google.com/uc?id=0def789lmn012"],
    brand: "Fitbit",
    color: "Slate Blue",
    type: "Fitness Tracker",
    },
    {
    name: "Fitbit sgfdgfdgdfgdfgfdgr",
    price: 12999,
    description: "Advanced fitness tracker with heart rate monitoring and built-in GPS.",
    stock: 35,
    images: ["https://drive.google.com/uc?id=9xyz123abc456", "https://drive.google.com/uc?id=0def789lmn012"],
    brand: "Fitbit",
    color: "Slate Blue",
    type: "Fitness Tracker",
    },
    {
    name: "Fitbit fdsfdsfsdfsdfsdfds",
    price: 12999,
    description: "Advanced fitness tracker with heart rate monitoring and built-in GPS.",
    stock: 35,
    images: ["https://drive.google.com/uc?id=9xyz123abc456", "https://drive.google.com/uc?id=0def789lmn012"],
    brand: "Fitbit",
    color: "Slate Blue",
    type: "Fitness Tracker",
    }
];


module.exports = objProducts;
